# Data Cleaning

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
file_path = '../data/raw/submission_data.csv'

train_data = pd.read_csv(file_path)
train_data

if 'submission' in file_path:
    train_data.drop(columns=['target'], inplace = True)

In [46]:
train_data.replace(-1, np.nan, inplace=True)
train_data.replace("-1", np.nan, inplace=True)
train_data

,brand,che_pc_usd,che_perc_gdp,cluster_nl,corporation,country,launch_date,date,drug_id,ind_launch_date,indication,insurance_perc_che,population,prev_perc,price_month,price_unit,public_perc_che,therapeutic_area
0,BRAND_E57A,2.079046,1.467920,BRAND_E57A_COUNTRY_06E4,CORP_01C7,COUNTRY_06E4,2022-02-01,2023-01-01,DRUG_ID_FADD,2022-08-01 00:00:00,['IND_C3B6'],1.000000,1.004739,0.036647,1.007091,1.012037,1.910448,THER_AREA_980E
1,BRAND_014B,2.079046,1.467920,BRAND_014B_COUNTRY_06E4,CORP_01C7,COUNTRY_06E4,2022-09-01,2023-01-01,DRUG_ID_E07F,NaN,['IND_A496'],1.000000,1.004739,0.106925,NaN,1.121625,1.910448,THER_AREA_6CEE
2,BRAND_1E6F,1.018268,1.108030,BRAND_1E6F_COUNTRY_4647,CORP_01C7,COUNTRY_4647,2022-05-01,2023-01-01,DRUG_ID_1A21,2022-06-01 00:00:00,"['IND_120F', 'IND_8E8D']",1.226667,3.243906,0.041152,NaN,1.005001,1.567164,THER_AREA_CD59
3,BRAND_9259,1.190075,1.515375,BRAND_9259_COUNTRY_FA79,CORP_01C7,COUNTRY_FA79,2022-12-01,2023-01-01,DRUG_ID_1315,NaN,['IND_BAFB'],1.785253,1.042681,0.002766,NaN,1.271214,1.786265,THER_AREA_6CEE
4,BRAND_106A,1.018876,1.127864,BRAND_106A_COUNTRY_E319,CORP_DF1B,COUNTRY_E319,2022-12-01,2023-01-01,DRUG_ID_2832,2020-03-01 00:00:00,['IND_5586'],1.076762,1.881992,0.000133,NaN,2.073953,1.223881,THER_AREA_96D7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764,BRAND_740F,2.709582,2.011926,BRAND_740F_COUNTRY_3AD0,CORP_01C7,COUNTRY_3AD0,2022-01-01,2023-12-01,DRUG_ID_C6D4,2022-08-01 00:00:00,['IND_C3B6'],1.573333,1.035514,0.027732,1.005218,1.020516,1.283582,THER_AREA_980E
1765,BRAND_056A,1.982740,1.915414,BRAND_056A_COUNTRY_4442,CORP_01C7,COUNTRY_4442,2022-09-01,2023-12-01,DRUG_ID_EC3A,2022-09-01 00:00:00,['IND_BAFB'],1.000000,1.179866,0.001275,1.248093,1.337647,1.837175,THER_AREA_96D7
1766,BRAND_F649,1.186954,1.493446,BRAND_F649_COUNTRY_9488,CORP_01C7,COUNTRY_9488,2023-11-01,2023-12-01,DRUG_ID_20C2,2024-11-01 00:00:00,['IND_F338'],1.815246,1.275586,0.007327,1.196712,1.287604,1.801799,THER_AREA_96D7
1767,BRAND_DB5A,1.186954,1.493446,BRAND_DB5A_COUNTRY_9488,CORP_01C7,COUNTRY_9488,2023-11-01,2023-12-01,DRUG_ID_2910,2024-11-01 00:00:00,['IND_F258'],1.815246,1.275586,0.527445,1.091414,1.604256,1.801799,THER_AREA_644A
1768,BRAND_106A,1.018876,1.127864,BRAND_106A_COUNTRY_E319,CORP_DF1B,COUNTRY_E319,2022-12-01,2023-12-01,DRUG_ID_2832,2020-03-01 00:00:00,['IND_5586'],1.076762,1.881992,0.000133,NaN,1.510381,1.223881,THER_AREA_96D7

In [47]:
variables = train_data.columns
print(f"There are {len(variables)} variables in the dataset and {len(train_data)} rows.")
variables

There are 18 variables in the dataset and 1769 rows.

Index(['brand', 'che_pc_usd', 'che_perc_gdp', 'cluster_nl', 'corporation',
       'country', 'launch_date', 'date', 'drug_id', 'ind_launch_date',
       'indication', 'insurance_perc_che', 'population', 'prev_perc',
       'price_month', 'price_unit', 'public_perc_che', 'therapeutic_area'],
      dtype='object')

In [48]:
na_counts = train_data.isna().sum()
na_percentage = (na_counts / len(train_data)) * 100
print(na_percentage)

brand                  0.000000
che_pc_usd             2.035048
che_perc_gdp           6.613906
cluster_nl             0.000000
corporation            0.000000
country                0.000000
launch_date            0.000000
date                   0.000000
drug_id                0.000000
ind_launch_date       21.198417
indication             0.000000
insurance_perc_che    15.036744
population             0.000000
prev_perc              0.000000
price_month           44.431882
price_unit             0.226116
public_perc_che        2.035048
therapeutic_area       0.000000
dtype: float64

In [49]:
vars_to_remove = ['cluster_nl', 'ind_launch_date']
train_data.drop(vars_to_remove, axis = 1, inplace = True)

In [50]:
# Convertir las columnas 'date' y 'launch_date' a formato de fecha
train_data['date'] = pd.to_datetime(train_data['date'])
train_data['launch_date'] = pd.to_datetime(train_data['launch_date'])

# Calcular la diferencia de tiempo en meses
train_data['time_difference'] = (train_data['date'] - train_data['launch_date']) / np.timedelta64(1, 'M')

# Mostrar las primeras filas para verificar
train_data[['date', 'launch_date', 'time_difference']].head()

        date launch_date  time_difference
0 2023-01-01  2022-02-01        10.774194
1 2023-01-01  2022-09-01         3.935484
2 2023-01-01  2022-05-01         7.903226
3 2023-01-01  2022-12-01         1.000000
4 2023-01-01  2022-12-01         1.000000

In [51]:
from sklearn.impute import KNNImputer

# Initialize the KNNImputer with k=7
imputer = KNNImputer(n_neighbors=7)
numerical_vars = train_data.select_dtypes(include=[np.number]).columns

# Impute the missing values
train_data_imputed = pd.DataFrame(imputer.fit_transform(train_data.select_dtypes(include=[np.number])), columns=numerical_vars)

# Assign the imputed values back to the original dataframe
train_data[numerical_vars] = train_data_imputed

# Display the imputed dataframe
train_data

,brand,che_pc_usd,che_perc_gdp,corporation,country,launch_date,date,drug_id,indication,insurance_perc_che,population,prev_perc,price_month,price_unit,public_perc_che,therapeutic_area,time_difference
0,BRAND_E57A,2.079046,1.467920,CORP_01C7,COUNTRY_06E4,2022-02-01,2023-01-01,DRUG_ID_FADD,['IND_C3B6'],1.000000,1.004739,0.036647,1.007091,1.012037,1.910448,THER_AREA_980E,10.774194
1,BRAND_014B,2.079046,1.467920,CORP_01C7,COUNTRY_06E4,2022-09-01,2023-01-01,DRUG_ID_E07F,['IND_A496'],1.000000,1.004739,0.106925,1.177787,1.121625,1.910448,THER_AREA_6CEE,3.935484
2,BRAND_1E6F,1.018268,1.108030,CORP_01C7,COUNTRY_4647,2022-05-01,2023-01-01,DRUG_ID_1A21,"['IND_120F', 'IND_8E8D']",1.226667,3.243906,0.041152,1.350090,1.005001,1.567164,THER_AREA_CD59,7.903226
3,BRAND_9259,1.190075,1.515375,CORP_01C7,COUNTRY_FA79,2022-12-01,2023-01-01,DRUG_ID_1315,['IND_BAFB'],1.785253,1.042681,0.002766,1.139768,1.271214,1.786265,THER_AREA_6CEE,1.000000
4,BRAND_106A,1.018876,1.127864,CORP_DF1B,COUNTRY_E319,2022-12-01,2023-01-01,DRUG_ID_2832,['IND_5586'],1.076762,1.881992,0.000133,1.171585,2.073953,1.223881,THER_AREA_96D7,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764,BRAND_740F,2.709582,2.011926,CORP_01C7,COUNTRY_3AD0,2022-01-01,2023-12-01,DRUG_ID_C6D4,['IND_C3B6'],1.573333,1.035514,0.027732,1.005218,1.020516,1.283582,THER_AREA_980E,22.548387
1765,BRAND_056A,1.982740,1.915414,CORP_01C7,COUNTRY_4442,2022-09-01,2023-12-01,DRUG_ID_EC3A,['IND_BAFB'],1.000000,1.179866,0.001275,1.248093,1.337647,1.837175,THER_AREA_96D7,14.709677
1766,BRAND_F649,1.186954,1.493446,CORP_01C7,COUNTRY_9488,2023-11-01,2023-12-01,DRUG_ID_20C2,['IND_F338'],1.815246,1.275586,0.007327,1.196712,1.287604,1.801799,THER_AREA_96D7,0.967742
1767,BRAND_DB5A,1.186954,1.493446,CORP_01C7,COUNTRY_9488,2023-11-01,2023-12-01,DRUG_ID_2910,['IND_F258'],1.815246,1.275586,0.527445,1.091414,1.604256,1.801799,THER_AREA_644A,0.967742
1768,BRAND_106A,1.018876,1.127864,CORP_DF1B,COUNTRY_E319,2022-12-01,2023-12-01,DRUG_ID_2832,['IND_5586'],1.076762,1.881992,0.000133,1.249494,1.510381,1.223881,THER_AREA_96D7,11.774194

In [52]:
from sklearn.preprocessing import StandardScaler

numerical_vars = numerical_vars.drop('target', errors='ignore')
scaler = StandardScaler()
train_data[numerical_vars] = scaler.fit_transform(train_data[numerical_vars])

In [53]:
train_data.to_csv('../data/processed/submission_data_processed_imputeKnn_scale.csv', index=False)